# Generated by Django 4.2.4 on 2023-10-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dweet',
        ),
    ]
