# Generated by Django 4.2.4 on 2023-10-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0003_dweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dweet',
        ),
    ]
