# Generated by Django 4.2.4 on 2023-09-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('dish_image', models.ImageField(upload_to='dishes')),
                ('price', models.IntegerField(default=150)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
