# Generated by Django 4.2.4 on 2023-10-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0005_dishes_delete_menutable_delete_testmodel1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
