# Generated by Django 4.2.4 on 2023-10-24 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0008_dishes_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('desc', models.TextField()),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('price', models.IntegerField(default=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homes.category')),
            ],
        ),
    ]
