# Generated by Django 4.2.4 on 2023-10-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0010_booking_delete_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
